sans: &sans sans

bar:
  location: top
  height: 26
  background: 00000066
  border:
    left-margin: 10
    right-margin: 10
    top-margin: 5
    bottom-margin: 5
  font: *sans

  right:
    - network:
        name: wlan0
        content:
          map:
            tag: state
            values:
              up: {string: {text: "{ssid}", right-margin: 8}}
              down: {string: {text: "No internet connection", right-margin: 8}}
    - clock:
        time-format: "%H:%M %Z"
        date-format: "%d/%m/%Y"
        content:
          - string: {text:  }
          - string: {text: "{date}", right-margin: 8}
          - string: {text:  }
          - string: {text: "{time}", right-margin: 8}

  center:
    - i3:
        content:
          current:
            - string: {text: "{application}"}
  left:
    - i3:
        content:
          "":
            map:
              tag: state
              default: {string: {text: "{name}", margin: 8}}
              values:
                focused:
                  string:
                    deco: {underline: {size: 2, color: FFFFFFFF}}
                    text: "{name}"
                    margin: 8
